//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderSong
    {
        public long ProviderSongID { get; set; }
        public long SongID { get; set; }
        public long ProviderID { get; set; }
        public string SongURL { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Song Song { get; set; }
    }
}
