//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public long UserRatingID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> SongID { get; set; }
        public Nullable<byte> Rating { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual User User { get; set; }
    }
}
